/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import javax.swing.JOptionPane;

/**
 *
 * @author PAKLAP.pk
 */
public class Admin_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Admin_dashboard
     */
    public Admin_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jOptionPane2 = new javax.swing.JOptionPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cancel1 = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        Admin_Admin = new javax.swing.JButton();
        Admin_customers = new javax.swing.JButton();
        Admin_booking = new javax.swing.JButton();
        Admin_Packages = new javax.swing.JButton();
        Admin_agents = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin Panel");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel2.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        cancel1.setBackground(new java.awt.Color(0, 0, 102));
        cancel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancel1.setForeground(new java.awt.Color(255, 255, 255));
        cancel1.setText("Cancel");
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        jPanel1.add(cancel1);
        cancel1.setBounds(450, 310, 115, 36);

        logout.setBackground(new java.awt.Color(0, 0, 102));
        logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(320, 310, 109, 36);

        panel1.setBackground(new java.awt.Color(102, 102, 102));
        panel1.setMaximumSize(new java.awt.Dimension(500, 500));
        panel1.setPreferredSize(new java.awt.Dimension(200, 200));
        panel1.setLayout(null);

        Admin_Admin.setBackground(new java.awt.Color(153, 204, 255));
        Admin_Admin.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Admin_Admin.setText("Admin");
        Admin_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_AdminActionPerformed(evt);
            }
        });
        panel1.add(Admin_Admin);
        Admin_Admin.setBounds(10, 60, 160, 40);

        Admin_customers.setBackground(new java.awt.Color(153, 204, 255));
        Admin_customers.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Admin_customers.setText("Customers");
        Admin_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_customersActionPerformed(evt);
            }
        });
        panel1.add(Admin_customers);
        Admin_customers.setBounds(10, 160, 160, 40);

        Admin_booking.setBackground(new java.awt.Color(153, 204, 255));
        Admin_booking.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Admin_booking.setText("Bookings");
        Admin_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_bookingActionPerformed(evt);
            }
        });
        panel1.add(Admin_booking);
        Admin_booking.setBounds(10, 210, 160, 40);

        Admin_Packages.setBackground(new java.awt.Color(153, 204, 255));
        Admin_Packages.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Admin_Packages.setText("Packages");
        Admin_Packages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_PackagesActionPerformed(evt);
            }
        });
        panel1.add(Admin_Packages);
        Admin_Packages.setBounds(10, 260, 160, 40);

        Admin_agents.setBackground(new java.awt.Color(153, 204, 255));
        Admin_agents.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Admin_agents.setText("Agents");
        Admin_agents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_agentsActionPerformed(evt);
            }
        });
        panel1.add(Admin_agents);
        Admin_agents.setBounds(10, 110, 160, 40);

        jPanel1.add(panel1);
        panel1.setBounds(0, 0, 186, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(716, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancel1ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int dialogButton = 0;
        // TODO add your handling code here
        int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to LogOut?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            User_login logout = new User_login();
            dispose();
            logout.show();
        }
        else
        {
            Admin_dashboard panel = new Admin_dashboard();
            dispose();
            panel.show();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void Admin_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_AdminActionPerformed
        // TODO add your handling code here:
        Admin_admin admin = new Admin_admin();
        dispose();
        admin.show();
    }//GEN-LAST:event_Admin_AdminActionPerformed

    private void Admin_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_customersActionPerformed
        // TODO add your handling code here:
        Admin_customer cust = new Admin_customer();
        dispose();
        cust.show();
    }//GEN-LAST:event_Admin_customersActionPerformed

    private void Admin_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_bookingActionPerformed
        // TODO add your handling code here:
        Admin_booking book = new Admin_booking();
        dispose();
        book.show();
    }//GEN-LAST:event_Admin_bookingActionPerformed

    private void Admin_PackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_PackagesActionPerformed
        // TODO add your handling code here:
        Admin_package pack = new Admin_package();
        dispose();
        pack.show();
    }//GEN-LAST:event_Admin_PackagesActionPerformed

    private void Admin_agentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_agentsActionPerformed
        // TODO add your handling code here:
        Admin_agent agent = new Admin_agent();
        dispose();
        agent.show();
    }//GEN-LAST:event_Admin_agentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_Admin;
    private javax.swing.JButton Admin_Packages;
    private javax.swing.JButton Admin_agents;
    private javax.swing.JButton Admin_booking;
    private javax.swing.JButton Admin_customers;
    private javax.swing.JButton cancel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
