/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author PAKLAP.pk
 */
public class Admin_agent extends javax.swing.JFrame {

    /**
     * Creates new form Admin_agent
     */
    public Admin_agent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        add_agent2 = new javax.swing.JButton();
        delete_agent = new javax.swing.JButton();
        search_agent = new javax.swing.JButton();
        update_agent1 = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        back = new javax.swing.JButton();
        panel3 = new java.awt.Panel();
        Admin_Admin = new javax.swing.JButton();
        Admin_customers = new javax.swing.JButton();
        Admin_booking = new javax.swing.JButton();
        Admin_Packages = new javax.swing.JButton();
        Admin_agents = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin Login");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(204, 204, 204));
        panel1.setLayout(null);

        add_agent2.setBackground(new java.awt.Color(255, 255, 255));
        add_agent2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        add_agent2.setText("Add Agent");
        add_agent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_agent2ActionPerformed(evt);
            }
        });
        panel1.add(add_agent2);
        add_agent2.setBounds(230, 90, 180, 40);

        delete_agent.setBackground(new java.awt.Color(255, 255, 255));
        delete_agent.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        delete_agent.setText("Delete Agent");
        delete_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_agentActionPerformed(evt);
            }
        });
        panel1.add(delete_agent);
        delete_agent.setBounds(440, 90, 190, 40);

        search_agent.setBackground(new java.awt.Color(255, 255, 255));
        search_agent.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        search_agent.setText("Search Agent");
        search_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_agentActionPerformed(evt);
            }
        });
        panel1.add(search_agent);
        search_agent.setBounds(440, 150, 190, 40);

        update_agent1.setBackground(new java.awt.Color(255, 255, 255));
        update_agent1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        update_agent1.setText("Update Agent");
        update_agent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_agent1ActionPerformed(evt);
            }
        });
        panel1.add(update_agent1);
        update_agent1.setBounds(230, 150, 180, 40);

        cancel.setBackground(new java.awt.Color(0, 0, 102));
        cancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        panel1.add(cancel);
        cancel.setBounds(510, 340, 115, 36);

        back.setBackground(new java.awt.Color(0, 0, 102));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        panel1.add(back);
        back.setBounds(380, 340, 109, 36);

        panel3.setBackground(new java.awt.Color(102, 102, 102));
        panel3.setMaximumSize(new java.awt.Dimension(500, 500));
        panel3.setPreferredSize(new java.awt.Dimension(200, 200));
        panel3.setLayout(null);

        Admin_Admin.setBackground(new java.awt.Color(153, 204, 255));
        Admin_Admin.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Admin_Admin.setText("Admin");
        Admin_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_AdminActionPerformed(evt);
            }
        });
        panel3.add(Admin_Admin);
        Admin_Admin.setBounds(10, 60, 160, 40);

        Admin_customers.setBackground(new java.awt.Color(153, 204, 255));
        Admin_customers.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Admin_customers.setText("Customers");
        Admin_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_customersActionPerformed(evt);
            }
        });
        panel3.add(Admin_customers);
        Admin_customers.setBounds(10, 160, 160, 40);

        Admin_booking.setBackground(new java.awt.Color(153, 204, 255));
        Admin_booking.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Admin_booking.setText("Bookings");
        Admin_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_bookingActionPerformed(evt);
            }
        });
        panel3.add(Admin_booking);
        Admin_booking.setBounds(10, 210, 160, 40);

        Admin_Packages.setBackground(new java.awt.Color(153, 204, 255));
        Admin_Packages.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Admin_Packages.setText("Packages");
        Admin_Packages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_PackagesActionPerformed(evt);
            }
        });
        panel3.add(Admin_Packages);
        Admin_Packages.setBounds(10, 260, 160, 40);

        Admin_agents.setBackground(new java.awt.Color(153, 204, 255));
        Admin_agents.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Admin_agents.setText("Agents");
        Admin_agents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_agentsActionPerformed(evt);
            }
        });
        panel3.add(Admin_agents);
        Admin_agents.setBounds(10, 110, 160, 40);

        panel1.add(panel3);
        panel3.setBounds(0, 10, 186, 390);

        getContentPane().add(panel1);
        panel1.setBounds(10, 80, 680, 410);

        jLabel4.setBackground(new java.awt.Color(0, 0, 102));
        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Agent");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 20, 690, 52);

        setSize(new java.awt.Dimension(716, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Admin_dashboard admin = new Admin_dashboard();
        dispose();
        admin.show();
    }//GEN-LAST:event_backActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void update_agent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_agent1ActionPerformed
        // TODO add your handling code here:
        update_agent agent = new update_agent();
        dispose();
        agent.show();
    }//GEN-LAST:event_update_agent1ActionPerformed

    private void search_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_agentActionPerformed
        // TODO add your handling code here:
        search_agent agent = new search_agent();
        dispose();
        agent.show();
    }//GEN-LAST:event_search_agentActionPerformed

    private void delete_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_agentActionPerformed
        // TODO add your handling code here:
        delete_agent agent = new delete_agent();
        dispose();
        agent.show();
    }//GEN-LAST:event_delete_agentActionPerformed

    private void add_agent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_agent2ActionPerformed
        // TODO add your handling code here:
        add_agent agent = new add_agent();
        dispose();
        agent.show();
    }//GEN-LAST:event_add_agent2ActionPerformed

    private void Admin_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_AdminActionPerformed
        // TODO add your handling code here:
        Admin_admin admin = new Admin_admin();
        dispose();
        admin.show();
    }//GEN-LAST:event_Admin_AdminActionPerformed

    private void Admin_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_customersActionPerformed
        // TODO add your handling code here:
        Admin_customer cust = new Admin_customer();
        dispose();
        cust.show();
    }//GEN-LAST:event_Admin_customersActionPerformed

    private void Admin_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_bookingActionPerformed
        // TODO add your handling code here:
        Admin_booking book = new Admin_booking();
        dispose();
        book.show();
    }//GEN-LAST:event_Admin_bookingActionPerformed

    private void Admin_PackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_PackagesActionPerformed
        // TODO add your handling code here:
        Admin_package pack = new Admin_package();
        dispose();
        pack.show();
    }//GEN-LAST:event_Admin_PackagesActionPerformed

    private void Admin_agentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_agentsActionPerformed
        // TODO add your handling code here:
        Admin_agent agent = new Admin_agent();
        dispose();
        agent.show();
    }//GEN-LAST:event_Admin_agentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_agent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_Admin;
    private javax.swing.JButton Admin_Packages;
    private javax.swing.JButton Admin_agents;
    private javax.swing.JButton Admin_booking;
    private javax.swing.JButton Admin_customers;
    private javax.swing.JButton add_agent2;
    private javax.swing.JButton back;
    private javax.swing.JButton cancel;
    private javax.swing.JButton delete_agent;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private java.awt.Panel panel1;
    private java.awt.Panel panel3;
    private javax.swing.JButton search_agent;
    private javax.swing.JButton update_agent1;
    // End of variables declaration//GEN-END:variables
}
