/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import javax.swing.JOptionPane;

/**
 *
 * @author PAKLAP.pk
 */
public class Agent_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Agent_dashboard
     */
    public Agent_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancel = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        Agent_agents = new javax.swing.JButton();
        Agent_customers = new javax.swing.JButton();
        Agent_booking = new javax.swing.JButton();
        Agent_Packages = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cancel1 = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        cancel.setBackground(new java.awt.Color(0, 0, 102));
        cancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 0, 102));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agent Panel");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel2.setOpaque(true);

        panel1.setBackground(new java.awt.Color(102, 102, 102));
        panel1.setMaximumSize(new java.awt.Dimension(500, 500));
        panel1.setPreferredSize(new java.awt.Dimension(200, 200));
        panel1.setLayout(null);

        Agent_agents.setBackground(new java.awt.Color(153, 204, 255));
        Agent_agents.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Agent_agents.setText("Agents");
        Agent_agents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agent_agentsActionPerformed(evt);
            }
        });
        panel1.add(Agent_agents);
        Agent_agents.setBounds(10, 80, 160, 40);

        Agent_customers.setBackground(new java.awt.Color(153, 204, 255));
        Agent_customers.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Agent_customers.setText("Customers");
        Agent_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agent_customersActionPerformed(evt);
            }
        });
        panel1.add(Agent_customers);
        Agent_customers.setBounds(10, 130, 160, 40);

        Agent_booking.setBackground(new java.awt.Color(153, 204, 255));
        Agent_booking.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Agent_booking.setText("Bookings");
        Agent_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agent_bookingActionPerformed(evt);
            }
        });
        panel1.add(Agent_booking);
        Agent_booking.setBounds(10, 180, 160, 40);

        Agent_Packages.setBackground(new java.awt.Color(153, 204, 255));
        Agent_Packages.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Agent_Packages.setText("Packages");
        Agent_Packages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agent_PackagesActionPerformed(evt);
            }
        });
        panel1.add(Agent_Packages);
        Agent_Packages.setBounds(10, 230, 160, 40);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        cancel1.setBackground(new java.awt.Color(0, 0, 102));
        cancel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancel1.setForeground(new java.awt.Color(255, 255, 255));
        cancel1.setText("Cancel");
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        jPanel2.add(cancel1);
        cancel1.setBounds(440, 290, 115, 36);

        logout.setBackground(new java.awt.Color(0, 0, 102));
        logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LogOut");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout);
        logout.setBounds(310, 290, 109, 36);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setSize(new java.awt.Dimension(716, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Agent_PackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agent_PackagesActionPerformed
        // TODO add your handling code here:
        Agent_package pack = new Agent_package();
        dispose();
        pack.show();
    }//GEN-LAST:event_Agent_PackagesActionPerformed

    private void Agent_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agent_bookingActionPerformed
        // TODO add your handling code here:
        Agent_booking book = new Agent_booking();
        dispose();
        book.show();
    }//GEN-LAST:event_Agent_bookingActionPerformed

    private void Agent_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agent_customersActionPerformed
        // TODO add your handling code here:
        Agent_customer cust = new Agent_customer();
        dispose();
        cust.show();
    }//GEN-LAST:event_Agent_customersActionPerformed

    private void Agent_agentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agent_agentsActionPerformed
        // TODO add your handling code here:
        Agent_agent agent = new Agent_agent();
        dispose();
        agent.show();
    }//GEN-LAST:event_Agent_agentsActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Agent_dashboard panel = new Agent_dashboard();
        dispose();
        panel.show();
    }//GEN-LAST:event_backActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancel1ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int dialogButton = 0;
        // TODO add your handling code here
        int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to LogOut?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
        User_login logout = new User_login();
        dispose();
        logout.show();
        }
        else
        {
           Agent_dashboard panel = new Agent_dashboard();
           dispose();
           panel.show();
        }
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agent_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agent_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agent_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agent_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agent_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agent_Packages;
    private javax.swing.JButton Agent_agents;
    private javax.swing.JButton Agent_booking;
    private javax.swing.JButton Agent_customers;
    private javax.swing.JButton back;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
